### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by Mae623** [Schwusch/widget_arrows#15]
Hello, when I use this package, I come across the bug.
`When the exception was thrown, this was the stack: 
#0      _ArrowElementState.initState (package:widget_arrows/widget_arrows.dart:333:73)
#1      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5015:57)
#2      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4853:5)
#3      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863:16)
#4      MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6435:36)
#5      MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6447:32)
...     Normal element mounting (4 frames)
#9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863:16)
#10     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6435:36)
#11     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6447:32)
...     Normal element mounting (4 frames)
#15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863:16)`

**Comment by Schwusch** [comment]
Hi, do you have a small example on how to reproduce the exception?
